### ISSUE TITLE
If puzzle can be solved without all of the pieces, should it be solved?

### ISSUE THREAD

**Issue by jbobrow** [scartier/blackout#1]
My assumption was that if a puzzle is given with 4 pieces, that it will require all 4 to be solved. If it can be solved with less than the 4 pieces, should it still celebrate?

I created a puzzle with 4 pieces, solved with 3, and then wondered what the 4th piece was for.

**Comment by jbobrow** [comment]
And now I have re-read the instructions and it appears this is by design. I'm curious to know how others respond to this. Now that I am thinking more about it, I like that you reward the alternate solutions... it is always frustrating to be told there is one right way to do things, I think you chose wisely here 🥇

**Comment by scartier** [comment]
Yeah puzzle generation uses all the tool tiles, but sometimes certain combinations mimic the same pattern as fewer. It doesn’t happen all the time, or even most of the time. When it does happen, and the player stumbles on it, I felt it should be rewarded.
