### ISSUE TITLE
Wake and Sleep animations are different from the system wake and sleep

### ISSUE THREAD

**Issue by jbobrow** [scartier/blackout#2]
Looks like they are missing the fade that is standard on the Blinks Game System

**Comment by scartier** [comment]
Ah yes. The dim() function, which is used by the wake/sleep animation, uses expensive divisions. I typically modify dim() to remove this in order to save precious code space. I would encourage the blink bios to switch to a more code-space-friendly algorithm.

That said, I will endeavor to restore it back to normal. I don't hold out much hope, though, as I had to scrape the barrel just to get the bit of polish requested to differentiate the puzzle tile.

I would appreciate suggestions for code optimization to address this.

**Comment by jbobrow** [comment]
Oooh, good catch, this is expensive and relatively simple to remove as dim is a convenience function, by no means a necessity. On this branch [here](https://github.com/jbobrow/blackout/tree/sleep-wake-anim), I removed the use of dim in the sleep and wake animations... however that only cuts about 80 bytes and we still need to recover another 73. I will take another look to see if I find some quick ways to recover that space and or make some suggestions of where to look for that space.

**Comment by jbobrow** [comment]
@scartier on this branch [here](https://github.com/jbobrow/blackout/pull/1), Josh identifies that "bitfields do save RAM, but also require extra code to pack and unpack the bits." When he made these small semantic changes, it seems that the program is not running correctly. Josh points out "Hmm… I think the only change in semantics would be if the code depended on the bitfields not being able to hold numbers that do not fit into the bitfield.  Does it do that anywhere?"

**Comment by scartier** [comment]
Thanks for looking into it! Trading data space for code space was on my list of things to try - especially after I had reclaimed some data storage from the unused datagram structures. Nice to know there's some hope there! I'll take a look at the branch soon to see what might be failing.

**Comment by scartier** [comment]
Just took a look. Unfortunately the bitfields in FaceValue need to stay that way because they map directly to the six bits of face value. The changes to ToolState shoooouuuuld work, I think. I'll take a look.

**Comment by scartier** [comment]
Okay! I took your changes to blinklib to bring back the blue fade during sleep/wake. I also took Josh's change to remove bitfields for ToolState. That seems to do the trick! I'll let you close the issue if you are satisfied. Thanks!

**Comment by jbobrow** [comment]
Wonderful, I'll load it up tonight, imagine that'll do it

**Comment by scartier** [comment]
Feel free to close if this is fixed to your satisfaction.
